remote-theme: pages-themes/cayman
plugins:
  - jekyll-seo-tag
title: BlenderProc Publication Visualization
description: Publication-ready visualization of 3D objects and point clouds in seconds.
url: https://hummat.github.io/bproc-pubvis
twitter:
  username: matthiashumt
  card: summary_large_image
logo: https://avatars.githubusercontent.com/u/22399283?v=4
image: https://hummat.github.io/bproc-pubvis/examples/mesh_depth.png
