name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `blenderproc run main.py ...`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command you ran (if applicable)
      render: bash
      placeholder: |
        blenderproc run main.py mesh.obj --save out.png --shading smooth

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of bproc-pubvis is affected?
      options:
        - Rendering
        - Mesh loading
        - Point cloud handling
        - Animation
        - Lighting/shading
        - Export
        - Other

  - type: input
    id: python-version
    attributes:
      label: Python Version
      placeholder: "e.g., 3.11.5"
    validations:
      required: true

  - type: input
    id: blender-version
    attributes:
      label: Blender/BlenderProc Version
      placeholder: "e.g., BlenderProc 2.8.0, Blender 4.2"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "e.g., Ubuntu 22.04, macOS 14, Windows 11"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste relevant error messages or logs
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
